version: '2'

services:
 db:
  image: mysql:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: "1542"
    MYSQL_USER: "root"
    MYSQL_PASSWORD: "1542"
    MYSQL_DATABASE: "cew"


